pragma Singleton

import QtQuick
import Quickshell

// GENERATED by matugen from config/matugen/templates/Colors.qml - do not edit.
// Edit the template, then change wallpaper to regenerate.
//
// Material Design 3 roles, camelCased. The M3 "on-" (content) roles end in
// "On" - primaryOn, surfaceOn, ... - because QML reserves on<Name> for signal
// handlers and refuses a property called onPrimary. Every other QML file reads colours from
// here (Colors.primary, Colors.onSurface, ...) - never hardcode a hex value.
Singleton {
    readonly property string mode: "{{mode}}"
    readonly property color sourceColor: "{{colors.source_color.default.hex}}"

    // Primary
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color primaryOn: "{{colors.on_primary.default.hex}}"
    readonly property color primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color primaryContainerOn: "{{colors.on_primary_container.default.hex}}"
    readonly property color primaryFixed: "{{colors.primary_fixed.default.hex}}"
    readonly property color primaryFixedDim: "{{colors.primary_fixed_dim.default.hex}}"
    readonly property color primaryFixedOn: "{{colors.on_primary_fixed.default.hex}}"
    readonly property color primaryFixedVariantOn: "{{colors.on_primary_fixed_variant.default.hex}}"

    // Secondary
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color secondaryOn: "{{colors.on_secondary.default.hex}}"
    readonly property color secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color secondaryContainerOn: "{{colors.on_secondary_container.default.hex}}"
    readonly property color secondaryFixed: "{{colors.secondary_fixed.default.hex}}"
    readonly property color secondaryFixedDim: "{{colors.secondary_fixed_dim.default.hex}}"
    readonly property color secondaryFixedOn: "{{colors.on_secondary_fixed.default.hex}}"
    readonly property color secondaryFixedVariantOn: "{{colors.on_secondary_fixed_variant.default.hex}}"

    // Tertiary
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color tertiaryOn: "{{colors.on_tertiary.default.hex}}"
    readonly property color tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color tertiaryContainerOn: "{{colors.on_tertiary_container.default.hex}}"
    readonly property color tertiaryFixed: "{{colors.tertiary_fixed.default.hex}}"
    readonly property color tertiaryFixedDim: "{{colors.tertiary_fixed_dim.default.hex}}"
    readonly property color tertiaryFixedOn: "{{colors.on_tertiary_fixed.default.hex}}"
    readonly property color tertiaryFixedVariantOn: "{{colors.on_tertiary_fixed_variant.default.hex}}"

    // Error
    readonly property color error: "{{colors.error.default.hex}}"
    readonly property color errorOn: "{{colors.on_error.default.hex}}"
    readonly property color errorContainer: "{{colors.error_container.default.hex}}"
    readonly property color errorContainerOn: "{{colors.on_error_container.default.hex}}"

    // Surfaces
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color backgroundOn: "{{colors.on_background.default.hex}}"
    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color surfaceDim: "{{colors.surface_dim.default.hex}}"
    readonly property color surfaceBright: "{{colors.surface_bright.default.hex}}"
    readonly property color surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"
    readonly property color surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    readonly property color surfaceVariant: "{{colors.surface_variant.default.hex}}"
    readonly property color surfaceTint: "{{colors.surface_tint.default.hex}}"
    readonly property color surfaceOn: "{{colors.on_surface.default.hex}}"
    readonly property color surfaceVariantOn: "{{colors.on_surface_variant.default.hex}}"

    // Outline, inverse, misc
    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color inverseSurface: "{{colors.inverse_surface.default.hex}}"
    readonly property color inverseOnSurface: "{{colors.inverse_on_surface.default.hex}}"
    readonly property color inversePrimary: "{{colors.inverse_primary.default.hex}}"
    readonly property color scrim: "{{colors.scrim.default.hex}}"
    readonly property color shadow: "{{colors.shadow.default.hex}}"

    // Same colour with a different opacity: Colors.alpha(Colors.scrim, 0.35)
    function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a);
    }
}
