-- Generated by matugen from the current wallpaper. Do not edit by hand.
-- This is the shipped default; matugen overwrites it on the next wallpaper
-- change. hyprland.lua loads it with a guarded dofile(), so deleting this file
-- is safe - you just fall back to the palette defined inside hyprland.lua.
return {
	primary   = "#75f1fa",
	secondary = "#00ff99",
	tertiary  = "#a277ff",
	outline   = "#595959",
	surface   = "#18181b",
	error     = "#e35149",
}
