pragma Singleton

import QtQuick
import Quickshell

// Layout constants shared by every component. Colours live in Colors.qml
// (generated by matugen) - never put a hex value anywhere else.
Singleton {
    readonly property string fontFamily: "JetBrainsMono Nerd Font"
    readonly property int fontSize: 13

    // Omarchy's documented bar size: a 26px full-width slab.
    readonly property int barHeight: 26
    // Panels (calendar, toasts, OSD) match your Hyprland window rounding;
    // the menu uses the 12px you asked for.
    readonly property int radius: 10
    readonly property int menuRadius: 12
    readonly property int gap: 8

    // Things that close themselves (milliseconds of no activity).
    readonly property int menuIdleMs: 30000      // menu
    readonly property int popupIdleMs: 15000     // calendar, notification history
    readonly property int toastMs: 5000          // normal notification
    readonly property int toastCriticalMs: 12000 // critical ones disappear too, just later

    // Colour temperature the night-light toggle applies (hyprsunset -t).
    readonly property int nightLightKelvin: 4000

    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")
    readonly property string stateHome: Quickshell.env("XDG_STATE_HOME") || (Quickshell.env("HOME") + "/.local/state")
}
